seml:
  executable: csdi/experiment.py
  name: tsdiff_csdi
  output_dir: experiments/logs
  project_root_dir: ../
  conda_environment: place_your_env_here

slurm:
  experiments_per_job: 2
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 2  # num cores
    time: 0-08:00     # max time, D-HH:MM
    partition: gpu_all

fixed:
  epochs: 200
  batch_size: 16
  lr: 1e-3
  layers: 4
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: 'quad'
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: 'random'

grid:
  seed:
    type: range
    min: 1
    max: 11
    step: 1

  testmissingratio:
    type: choice
    options:
      - 0.1
      - 0.5
      - 0.9

  nsample:
    type: choice
    options:
      - 20

baseline:
  fixed:
    gp_noise: False

our:
  fixed:
    gp_noise: True

  grid:
    gp_sigma:
      type: choice
      options:
        - 0.005
        - 0.01
        - 0.02
        - 0.05
        - 0.1
